name: elemental


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio:
  geolocator:
  flutter_bloc:
  get_it:
  lottie:
  iconsax:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/weather/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # example:
  fonts:
    - family: manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Light.ttf
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
        - asset: assets/fonts/manrope/Manrope-Bold.ttf

    - family: Trajan Pro
      fonts:
         - asset: assets/fonts/app_icons/AppIcons.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
