name: 🌟 Feature Request
description: Submit a feature request
title: "[Feature]: <title>"
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this feature request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the new feature in detail.
      placeholder: Provide a comprehensive overview of the proposed feature.
    validations:
      required: true
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Outline the use cases or scenarios where this feature would be beneficial.
      placeholder: Describe specific situations where the feature would be valuable.
    validations:
      required: false
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Explain the benefits of implementing this feature.
      placeholder: Describe how users and the project would benefit from this addition.
    validations:
      required: true
